<?php
return array(
	//'配置项'=>'配置值'
	'menuJson'=>'{
		      "button":[
		      {
		           "name":"途虎商城",
		           "sub_button":[
		            {
		               "type":"click",
		               "name":"北京天气",
		               "key":"天气北京"
		            },
		            {
		               "type":"click",
		               "name":"深圳天气",
		               "key":"天气深圳"
		            },
		            {
		                "type":"view",
		                "name":"本地天气",
		                "url":"http://m.hao123.com/a/tianqi"
		            }]
		       },
		       {
		           "name":"车侣威擎",
		           "sub_button":[
		            {
		               "type":"click",
		               "name":"公司简介",
		               "key":"company"
		            },
		            {
		               "type":"click",
		               "name":"避免刮伤",
		               "key":"刮伤"
		            },
		            {
		                "type":"click",
		                "name":"讲个笑话",
		                "key":"笑话"
		            }]
		       },		       
		       {
		           "name":"更多",
		           "sub_button":[
		            {
		               "type":"view",
		               "name":"违章查询",
		               "url":"http://t.cn/RvDTIdz"
		            },
		            {
		               "type":"view",
		               "name":"高速路况",
		               "url":"http://t.cn/Rykc5qP"
		            },
		            {
		                "type":"view",
		                "name":"各地天气",
		                "url":"http://t.cn/RykccaW"
		            }]
		       }
		      ]
		 }',
);