<?php
return array(
	//'配置项'=>'配置值'
	//
	'SRC'=>"http://wx.vlegend.cn/Public",
	//微信菜单
	'menuJson'=>'{
		      "button":[
		      {
		           "name":"关于爱车",
		           "sub_button":[
		            {
		               "type":"click",
		               "name":"我要硬件",
		               "key":"hongbao"
		            },
		            {
		               "type":"click",
		               "name":"我要软件",
		               "key":"天气深圳"
		            },
		            {
		               "type":"view",
		               "name":"违章查询",
		               "url":"http://t.cn/RvDTIdz"
		            }
		            ]
		       },
		       {
				"type":"view",
				"name":"讲个笑话",
				"url":"http://t.cn/RUDmi8I"
		       },		       
		       {
		           "name":"积分兑换",
		           "sub_button":[
		            {
		               "type":"view",
		               "name":"规则",
		               "url":"http://t.cn/RvDTIdz"
		            },
		            {
		               "type":"view",
		               "name":"签到",
		               "url":"http://t.cn/Rykc5qP"
		            },
		            {
		                "type":"view",
		                "name":"积分排名",
		                "url":"http://t.cn/RykccaW"
		            }，
		            {
		                "type":"view",
		                "name":"积分排名",
		                "url":"http://t.cn/RykccaW"
		            },
		            {
		                "type":"view",
		                "name":"我要打榜",
		                "url":"http://t.cn/RykccaW"
		            },
					{
		                "type":"view",
		                "name":"兑换",
		                "url":"http://t.cn/RykccaW"
		            }]
		       }
		      ]
		 }',
);